apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lineup-service-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/cyc2045/lineup-service-demo.git
    targetRevision: HEAD
    path: helm
    helm:
      valueFiles:
        - values.yaml
        - npd/values.yaml
      # PARAMETERS SECTION REMOVED TO ALLOW AUTOMATIC UPDATES
  destination:
    server: https://kubernetes.default.svc
    namespace: lineup-dev
