apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lineup-service-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/cyc2045/lineup-service-demo.git
    targetRevision: HEAD
    path: helm
    helm:
      valueFiles:
        - values.yaml
        - npd/values.yaml
      # ADD THIS SECTION BELOW
      parameters:
        - name: "image.tag"
          value: "v0.0.0" # The GitHub Action will look for this 'value:' line
  destination:
    server: https://kubernetes.default.svc
    namespace: lineup-dev
